### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zolamk**

### CODE REVIEW

**Comment by zolamk** [comment]
testing

**Comment by zolamk** [comment]
test 1

**Comment by zolamk** [comment]
test 1

**Comment by zolamk** [comment]
test 2

**Comment by zolamk** [comment]
test 3

**Comment by zolamk** [comment]
test 4

**Comment by zolamk** [comment]
test 1

**Comment by zolamk** [comment]
test 2

**Comment by zolamk** [comment]
test 3

**Comment by zolamk** [comment]
test 4

**Comment by zolamk** [comment]
test 5

**Review by xulamek — APPROVED** [review]
LGTM

**Review by zolate — APPROVED** [review]

**Review by zolate — COMMENTED** [review]
We should consider refactoring this

**Comment by zolamk** [comment]
properly approved

**Pull request closed without merging**
